### ISSUE TITLE
Exception: {"Could not extract video author."}

### ISSUE THREAD

**Issue by zjjohncq** [Tyrrrz/YoutubeDownloader#239]
### Version

ver 1.8.3

### Details

when download playlist : https://www.youtube.com/playlist?list=PLxpE_d3Yh0l9xKJwdhzDzMc23JOZdbTwg
get exception at 
>	YoutubeDownloader.dll!YoutubeDownloader.Services.QueryService.ExecuteQueryAsync(YoutubeDownloader.Models.Query query) Line 66	C#
var videos = await _youtube.Playlists.GetVideosAsync(query.Value);

Exception 
  | Message | "Could not extract video author." 
stackTrace
   at YoutubeExplode.Playlists.PlaylistClient.<GetVideoBatchesAsync>d__4.MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Playlists\PlaylistClient.cs:line 115
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at YoutubeExplode.Playlists.PlaylistClient.<GetVideoBatchesAsync>d__4.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.<SelectManyAsync>d__1`2.MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\AsyncEnumerableExtensions.cs:line 32
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.<SelectManyAsync>d__1`2.MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\AsyncEnumerableExtensions.cs:line 32
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.<SelectManyAsync>d__1`2.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.<ToListAsync>d__3`1.MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\AsyncEnumerableExtensions.cs:line 51
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at YoutubeExplode.Utils.Extensions.AsyncEnumerableExtensions.<ToListAsync>d__3`1.MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Utils\Extensions\AsyncEnumerableExtensions.cs:line 51
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at YoutubeExplode.Common.BatchItemExtensions.<CollectAsync>d__0`1.MoveNext() in D:\a\YoutubeExplode\YoutubeExplode\YoutubeExplode\Common\IBatchItem.cs:line 30
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at YoutubeDownloader.Services.QueryService.<ExecuteQueryAsync>d__3.MoveNext() in C:\Applications\youtubeDownloadFromGitHub\YoutubeDownloader-1.8.3\YoutubeDownloader\Services\QueryService.cs:line 66
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YoutubeDownloader.Services.QueryService.<ExecuteQueriesAsync>d__4.MoveNext() in C:\Applications\youtubeDownloadFromGitHub\YoutubeDownloader-1.8.3\YoutubeDownloader\Services\QueryService.cs:line 99
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YoutubeDownloader.ViewModels.RootViewModel.<ProcessQuery>d__37.MoveNext() in C:\Applications\youtubeDownloadFromGitHub\YoutubeDownloader-1.8.3\YoutubeDownloader\ViewModels\RootViewModel.cs:line 162

### Steps to reproduce

download playlist :
https://www.youtube.com/playlist?list=PLxpE_d3Yh0l9xKJwdhzDzMc23JOZdbTwg

**Comment by zjjohncq** [comment]
This is because of the extracted play list did not exclude the deleted videos which cause the problem
