### ISSUE TITLE
Failing to download a video due to closed captions parsing error

### ISSUE THREAD

**Issue by xs2237** [Tyrrrz/YoutubeDownloader#362]
### Version

v1.10.1

### Platform

Windows 10

### Steps to reproduce

Video URL: https://www.youtube.com/watch?v=TqxQru7bdt0

Download settings:
- 1080p (mp4)

Application settings:
- Nothing changed from the initial state.

Steps:
- Just download.

### Details

Some videos fail to download.
There seems to be something wrong with the subtitles.

Error message:
```
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Parse(String text, LoadOptions options)
   at YoutubeExplode.Utils.Xml.Parse(String source) in /_/YoutubeExplode/Utils/Xml.cs:line 9
   at YoutubeExplode.Bridge.ClosedCaptionTrackResponse.Parse(String raw) in /_/YoutubeExplode/Bridge/ClosedCaptionTrackResponse.cs:line 75
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionController.GetClosedCaptionTrackResponseAsync(String url, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/ClosedCaptions/ClosedCaptionController.cs:line 25
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.GetClosedCaptionsAsync(ClosedCaptionTrackInfo trackInfo, CancellationToken cancellationToken)+MoveNext() in /_/YoutubeExplode/Videos/ClosedCaptions/ClosedCaptionClient.cs:line 68
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.GetClosedCaptionsAsync(ClosedCaptionTrackInfo trackInfo, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.ToListAsync[T](IAsyncEnumerable`1 source) in /_/YoutubeExplode/Utils/Extensions/AsyncCollectionExtensions.cs:line 48
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.ToListAsync[T](IAsyncEnumerable`1 source) in /_/YoutubeExplode/Utils/Extensions/AsyncCollectionExtensions.cs:line 48
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.GetAsync(ClosedCaptionTrackInfo trackInfo, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/ClosedCaptions/ClosedCaptionClient.cs:line 121
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.WriteToAsync(ClosedCaptionTrackInfo trackInfo, TextWriter writer, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/ClosedCaptions/ClosedCaptionClient.cs:line 143
   at YoutubeExplode.Videos.ClosedCaptions.ClosedCaptionClient.DownloadAsync(ClosedCaptionTrackInfo trackInfo, String filePath, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/ClosedCaptions/ClosedCaptionClient.cs:line 181
   at YoutubeExplode.Converter.Converter.PopulateSubtitleInputsAsync(String baseFilePath, IReadOnlyList`1 closedCaptionTrackInfos, ICollection`1 subtitleInputs, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode.Converter/Converter.cs:line 218
   at YoutubeExplode.Converter.Converter.ProcessAsync(String filePath, Container container, IReadOnlyList`1 streamInfos, IReadOnlyList`1 closedCaptionTrackInfos, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode.Converter/Converter.cs:line 264
   at YoutubeExplode.Converter.ConversionExtensions.DownloadAsync(VideoClient videoClient, IReadOnlyList`1 streamInfos, IReadOnlyList`1 closedCaptionTrackInfos, ConversionRequest request, IProgress`1 progress, CancellationToken cancellationToken) in /_/YoutubeExplode.Converter/ConversionExtensions.cs:line 81
   at YoutubeDownloader.Core.Downloading.VideoDownloader.DownloadVideoAsync(String filePath, IVideo video, VideoDownloadOption downloadOption, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\YoutubeDownloader\YoutubeDownloader\YoutubeDownloader.Core\Downloading\VideoDownloader.cs:line 58
   at YoutubeDownloader.ViewModels.Components.DashboardViewModel.<>c__DisplayClass31_0.<<EnqueueDownload>b__0>d.MoveNext() in D:\a\YoutubeDownloader\YoutubeDownloader\YoutubeDownloader\ViewModels\Components\DashboardViewModel.cs:line 110
```

### Checklist

- [X] I have looked through existing open and closed issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
I'm getting this right now.

![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/1935960/e744303a-90c2-424a-be8a-f5f59e08fc11)

**Comment by xs2237** [comment]
I checked again here, but there was no problem watching the video.
![ss_202308150931](https://github.com/Tyrrrz/YoutubeDownloader/assets/12760572/eeb497d6-1233-47ae-aa4e-b2257ddd0054)

**Comment by xs2237** [comment]
The video contributor may have restrictions on which countries can be viewed.

https://support.google.com/youtube/answer/6303378?hl=en

**Comment by Tyrrrz** [comment]
Hmm, I switched my location to Japan/Tokyo via VPN and I was able to download the video just fine:

![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/1935960/6c6fa1f8-7b4e-4f99-9d3d-b9b5ff0c6366)

You can try the latest CI build, e.g.: https://github.com/Tyrrrz/YoutubeDownloader/suites/15052712649/artifacts/859584208

But I don't think there's anything that changed related to that.

**Comment by xs2237** [comment]
I tried again today and both the latest and CI builds successfully downloaded the video.✅

Other than that, I have some additional information that might help fix this bug that I will post later.

**Comment by xs2237** [comment]
With another video, the problem reappeared.
The error detail is exactly the same as last time.

Video URL: https://www.youtube.com/watch?v=OxywFSRHcUk
![image](https://github.com/Tyrrrz/YoutubeDownloader/assets/12760572/1608929a-ccee-4455-be16-fc1d6e84f7d7)
