### ISSUE TITLE
Some videos cannot be downloaded due to 403 Forbidden error

### ISSUE THREAD

**Issue by Jason14159** [Tyrrrz/YoutubeDownloader#469]
### Version

1.12.2

### Platform

windows 11

### Steps to reproduce

System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at YoutubeExplode.Videos.Streams.StreamClient.TryGetContentLengthAsync(IStreamData streamData, String url, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 63
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamInfosAsync(IEnumerable`1 streamDatas, CancellationToken cancellationToken)+MoveNext() in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 114
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamInfosAsync(IEnumerable`1 streamDatas, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.ToListAsync[T](IAsyncEnumerable`1 source) in /_/YoutubeExplode/Utils/Extensions/AsyncCollectionExtensions.cs:line 49
   at YoutubeExplode.Utils.Extensions.AsyncCollectionExtensions.ToListAsync[T](IAsyncEnumerable`1 source) in /_/YoutubeExplode/Utils/Extensions/AsyncCollectionExtensions.cs:line 49
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamInfosAsync(VideoId videoId, PlayerResponse playerResponse, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 218
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamInfosAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 276
   at YoutubeExplode.Videos.Streams.StreamClient.GetManifestAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/Streams/StreamClient.cs:line 292
   at YoutubeDownloader.Core.Downloading.VideoDownloader.GetDownloadOptionsAsync(VideoId videoId, CancellationToken cancellationToken) in /home/runner/work/YoutubeDownloader/YoutubeDownloader/YoutubeDownloader.Core/Downloading/VideoDownloader.cs:line 25
   at YoutubeDownloader.Core.Downloading.VideoDownloader.GetBestDownloadOptionAsync(VideoId videoId, VideoDownloadPreference preference, CancellationToken cancellationToken) in /home/runner/work/YoutubeDownloader/YoutubeDownloader/YoutubeDownloader.Core/Downloading/VideoDownloader.cs:line 35
   at YoutubeDownloader.ViewModels.Components.DashboardViewModel.EnqueueDownload(DownloadViewModel download, Int32 position) in /home/runner/work/YoutubeDownloader/YoutubeDownloader/YoutubeDownloader/ViewModels/Components/DashboardViewModel.cs:line 101

### Details

When downloading a playlist, this error occurs for some of the videos. Some can be downloaded and some cannot.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Molices** [comment]
I have the same problem, what should I do???

**Comment by Tyrrrz** [comment]
Superseded by #513
