### ISSUE TITLE
Can not download video  `Video is not available` error

### ISSUE THREAD

**Issue by WeihanLi** [Tyrrrz/YoutubeDownloader#482]
### Version

1.12.2

### Platform

Windows 11

### Steps to reproduce

just try to download video

https://www.youtube.com/watch?v=vXnTMjMe5Eg
https://www.youtube.com/watch?v=_zjdBTJit4Q
https://www.youtube.com/watch?v=yMGTUQhjtlM

### Details

![image](https://github.com/user-attachments/assets/4c175fd4-2ee2-4bd6-87f7-4ce07fb5d0a0)

Error stack trace from debug

```
YoutubeExplode.Exceptions.VideoUnavailableException: Video 'vXnTMjMe5Eg' is not available.
   at YoutubeExplode.Videos.VideoController.GetVideoWatchPageAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/VideoController.cs:line 39
   at YoutubeExplode.Videos.VideoClient.GetAsync(VideoId videoId, CancellationToken cancellationToken) in /_/YoutubeExplode/Videos/VideoClient.cs:line 37
   at YoutubeDownloader.Core.Resolving.QueryResolver.TryResolveVideoAsync(String query, CancellationToken cancellationToken) in C:\projects\source\YoutubeDownloader\YoutubeDownloader.Core\Resolving\QueryResolver.cs:line 51
```

not sure if it relates to #476 , feel free to close if duplicated

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the application
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by mjq1712726683** [comment]
右上角那里点下钥匙那里登录的微软账号即可

**Comment by WeihanLi** [comment]
> 右上角那里点下钥匙那里登录的微软账号即可

登录之后可以下载，谢谢

**Comment by WeihanLi** [comment]
seemed related to https://github.com/Tyrrrz/YoutubeExplode/issues/794 closed as duplicated
